name: CI
on:
    push:
        branches:
            - main
            - master
jobs:
    build:
        name: Build on ${{ matrix.node }} and ${{ matrix.os }}
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # node: ['16.x', '12.x', '14.x']
                # os: [ubuntu-latest, windows-latest, macOS-latest]
                node: ['12.x']
                os: [ubuntu-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1

            # - name: Lint
            #   run: yarn lint

            - name: Test
              run: yarn test --ci --coverage --maxWorkers=2

            - name: Build
              run: yarn build
